### ISSUE TITLE
How do I use dynamic subroutes with this component?

### ISSUE THREAD

**Issue by jlamim** [samturrell/vue-breadcrumbs#14] opened 2017-10-24 13:41 UTC
I need to use something like this:

`
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    },
    {
      path: '/informativos',
      name: 'Informativos',
      component: Informativos,
      meta: {
        breadcrumb: 'Informativos'
      },
      children: [
        {
          path: '/informativo/:id/:title',
          component: InformativoDetalhes,
          meta: {
            breadcrumb: 'Título'
          }
        }
      ]
    }
  ]
})
`

**Comment by samturrell** [comment] 2017-11-13 13:04
Duplicate of #1 I believe.

**Closed as completed** 2017-11-13 13:04 UTC
Labels: duplicate
